name: cart_repository
description: local repository 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter_lints: ^2.0.1
  cart_api:
    path: ../cart_api

