name: remote_products_api
description: product api
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  connectivity_plus: ^2.3.3
  api_util:
    path: ../../api_util
  product_api:
    path: ../product_api
  local_storage_auth_api:
    path: ../../auth/local_storage_auth_api

dev_dependencies:
  coverage: ^1.1.0
  flutter_lints: ^2.0.1
  build_runner: ^2.1.10
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
