name: local_storage_cart_api
description: local repository 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
      sdk: flutter
  flutter_lints: ^2.0.1
  meta: ^1.3.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.7
  cart_api:
    path: ../cart_api

