name: local_storage_auth_api
description: localstorage api
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  shared_preferences: ^2.0.15
  flutter_lints: ^2.0.1
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  
