name: auth_repository
description: product repository 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  auth_api:
    path: ../auth_api
  
dev_dependencies:
  coverage: ^1.1.0
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.19.2
