// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_UEiQrmke--tMlRIl3lg8WggWNvVtiIs',
    appId: '1:486482974238:web:494e6a1dea7b6a95c2400f',
    messagingSenderId: '486482974238',
    projectId: 'ecommerce-app-b4734',
    authDomain: 'ecommerce-app-b4734.firebaseapp.com',
    storageBucket: 'ecommerce-app-b4734.appspot.com',
    measurementId: 'G-5G4KY84282',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg6oOd2k2DOL8HxuxDnmYR-qN3mrmwS4k',
    appId: '1:486482974238:android:d33f0015c64a4553c2400f',
    messagingSenderId: '486482974238',
    projectId: 'ecommerce-app-b4734',
    storageBucket: 'ecommerce-app-b4734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqza2J8t2Lzg3T_U2NkRcSQtE9-aMWBg',
    appId: '1:486482974238:ios:10e0f5dd261c2a1dc2400f',
    messagingSenderId: '486482974238',
    projectId: 'ecommerce-app-b4734',
    storageBucket: 'ecommerce-app-b4734.appspot.com',
    iosClientId: '486482974238-kvdkqve01tngvvrubqo4mvmiuriqj959.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFqza2J8t2Lzg3T_U2NkRcSQtE9-aMWBg',
    appId: '1:486482974238:ios:10e0f5dd261c2a1dc2400f',
    messagingSenderId: '486482974238',
    projectId: 'ecommerce-app-b4734',
    storageBucket: 'ecommerce-app-b4734.appspot.com',
    iosClientId: '486482974238-kvdkqve01tngvvrubqo4mvmiuriqj959.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );
}
